name: auto-testing-model
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: checking-train-script
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python src/testing_train.py
