name: testing-train-script
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: [ubuntu-latest]
    env:
      GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
      NEPTUNE_PROJECT_NAME: ${{ secrets.NEPTUNE_PROJECT_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Using Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: checking-train-script
        working-directory: ./src
        run: |
          python train.py
